multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 64, in par_pt_iters
    namelist, decomp_method=decomp_method, chkpt=True)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_permtest.py", line 33, in permutation_testing
    CCA_res = lindecomp(X,Y,reg_val=reg_val,param_search=False)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_brainrep.py", line 126, in comp_CCA
    CCA_res.ws[0] = VX @ CCA_res.ws[0]
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 100 is different from 1003)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 106, in <module>
    run_parallel_permtests(output_basedir,n_workers)
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 85, in run_parallel_permtests
    P.map(par_pt_iters,worker_spec)
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 100 is different from 1003)
