multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 75, in par_pt_iters
    namelist, decomp_method=decomp_method, chkpt=True)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_permtest.py", line 32, in permutation_testing
    CCA_res = lindecomp(X,Y,reg_val=reg_val,param_search=False)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_brainrep.py", line 99, in comp_CCA
    kernelcca = False)
TypeError: __init__() got an unexpected keyword argument 'numCCs'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 112, in <module>
    decomp_vals,pt_arch_dir = run_parallel_permtests(output_basedir,n_workers)
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 94, in run_parallel_permtests
    P.map(par_pt_iters,worker_spec)
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: __init__() got an unexpected keyword argument 'numCCs'
