Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_SSpHom.py", line 7, in <module>
    SSH.comp_perst_imgs(sys.argv[2],fname_out=sys.argv[5])
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/SubjSubjHomologies.py", line 93, in comp_perst_imgs
    pf.export_dists(fname_out,fig_path)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/phom_figs.py", line 42, in export_dists
    save_w_colorbar(D,img_name)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/phom_figs.py", line 58, in save_w_colorbar
    im = plt.imshow(img_data) # Show the image
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2730, in imshow
    **kwargs)
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5523, in imshow
    im.set_data(X)
  File "/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/matplotlib/image.py", line 712, in set_data
    .format(self._A.shape))
TypeError: Invalid shape (5, 3, 400) for image data
